### ISSUE TITLE
Missing script in Player Object

### ISSUE THREAD

**Issue by krtp0028** [kyrieyang23/roy#17]
A missing script in Player Object. Look like it is supposed to be PlayerLocomotion.cs but the animation doesn't work and moving backward still makes the model float.

**Comment by kyrieyang23** [comment]
ตอนนี้ model มันยัง float อยู่ถ้าเปลี่ยนมุมกล้อง มันต้อง script camera ให้เสร็จก่อน

**Comment by kyrieyang23** [comment]
ใช่ ตอนนี้เปลี่ยน file player manager ไปอยู่ใน locomotion แทน
