### ISSUE TITLE
Player mouse following not working

### ISSUE THREAD

**Issue by krtp0028** [kyrieyang23/roy#9]
พอเอาเมาส์ไปวางไว้ฝั่งบนของจอ หน้าตัวละครไม่หันตาม

**Comment by tontosirikul** [comment]
การหันของตัวละครคำนวณมุมจากตำแหน่งของวัตถุจาก global camera การชี้ไปที่โล่งไม่สามารถคำนวณมุมได้ 
โดยเราสามารถทำให้จอเราคลุมแมพทั้งหมดเพื่อทำให้เราไม่สามารถชี้พื้นที่โล่งได้

**Comment by kyrieyang23** [comment]
เอาใหม่ๆ ตอนนี้ตัวละครมันหันหน้าตามเมาส์ เวลาควบคุมตอนเดินแล้วมันควบคุมได้ยาก อยากให้เปลี่ยนจากมันหันหน้าตามเมาส์เป็นอันหน้าตามที่เดินแทน เช่น กด wa พร้อมกัน ตัวละครจะต้องหันเฉียงไปทางซ้ายบนเลยตามทิศที่เดิน

**Comment by tontosirikul** [comment]
Thanks for your elaboration, งั้นฝากเทส Branch iss9 หน่อยครับว่าใช่ที่บอกแบบที่บอกไหม ถ้าใช่รบกวน merge PR  ที่เปิด เข้า main หน่อยนะ
